INSERT INTO RecipeEntity (id, name, vegeterian, servings, ingredients, instructions)  VALUES
  (1, 'Maggie Noodles', 'Yes', 2, '1 maggie, 1tbsp butter, 250ml water', 'Boil water and tastemaker sachet in a saucepan. Add noodle cake and buuter to it and cook for 10 mins.'),
  (2, 'Coffee', 'Yes', 1, '1 tbsp coffee powder, 1 tsp sugar, 150ml milk or creamer', 'Heat milk with sugar and coffee in a saucepan. Pour in a cup and serve'),
  (3, 'Pumpkin Soup', 'Yes', 2, '2 tbsp olive oil,2 onions,1kg pumpkin peeled, deseeded and chopped into chunks, 700ml vegetable stock, 150ml cream', 'Heat oil in a saucepa and  onions for 5 mins. Add pumpkin and cook for 8-10 mins.Pour vegetable stock with salt and pepper. Add double cream into the pan and puree with a blender.'),
  (4, 'Dal Makahani', 'Yes', 4, '140 gm black gram, 40 gm kidney beans, 750 ml water, 1 cup chopped onions,1 green chilly, 2 tbsp Ginger Garlic Paste, 2 Tomatoes, 2 Clove, 1 Cinnamon, 1 Cardamom, 3 tbsp Butter', 'In a pan heat butter with cloves,cardamoms,cinnamon. Add onions, chillies & ginger garlic paste and cook till brown. Add the prepared tomato puree and cook for 10 mins.Then add the cooked urad dal and rajma beans along with stock and water.'),
  (5, 'Banana Bread', 'No', 4, '4 Bananas, 2 eggs, 1 tsp cinnamom powder, 200 gm Sugar, 1 tsp Vanilla essence, 180 gm flour, 2 tsp baking powder', 'Preheat the oven to 180 degrees.Take sliced bananas,sugar,eggs,cinnamom and vanilla in a mixing bowl and puree them with a hand blender. Sieve flour, baking powder in the bowl and mix.Pour the bread mixture into greased loaf pan and bake'),
  (6, 'Chicken Steak', 'No', 1, '4 chicken pieces, 2 Eggs (slightly whisked),1 tsp ginger garlic paste,1 cup onions, 2 tbsp coriander leaves, 2 green chillies,1 tsp black pepper powder,2 tbsp flour, 1 tbsp vinegar, salt, butter', 'Flatten the chicken and mix with the other ingredients, except oil and marinate for 2 hours.Heat a non-stick pan with thin layer of oil.When hot, place chicken in it and cook till tender and brown on both sides.'),
  (7, 'Cheese Toast', 'yes', 8, '1 tbsp butter, 1 cup shredded Cheddar cheese, 1 cup shredded mozzarella cheese, 8 slices Bread', 'Preheat oven to 375 degree ferhenheit. Spread all slices of bread with 1 teaspoon softened butter; sprinkle with Cheddar and mozzarella cheese. Bake on a baking sheet until cheese melts and edges begin to brown.'),
  (8, 'PB&J sandwich', 'yes', 1, '2 tbsp peanut butter,1 tbsp fruit jam,2 slices Bread', 'Spread the peanut butter on one piece of bread.Spread the jelly on the other side.Put the two pieces of bread together to form a sandwich.'),
  (9, 'Omlette', 'No', 1, '3 eggs beaten, 2 tsp butter, pinch of salt and pepper', 'SSeason the beaten eggs with salt and pepper. Melt butter in a non-stick frying pan over a low heat. Pour the eggs into the pan and cook till golden brown.');